# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 13:15
from __future__ import unicode_literals

import autodidact.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0007_auto_20170308_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='autodidact.Page')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
    ]
