# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0010_clear_obsolete_cdns_from_pandocfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='degree',
            field=models.PositiveIntegerField(choices=[(10, 'Bachelor'), (20, 'Pre-master'), (30, 'Master')], default=10),
            preserve_default=False,
        ),
    ]
