# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0011_programme_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
