# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0012_programme_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
