# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0014_auto_20171018_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='autodidact.Tag'),
        ),
    ]
