# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import pandocfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0015_auto_20171018_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
    ]
