# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0015_auto_20160307_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='users',
            new_name='students',
        ),
    ]
