# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0016_auto_20171018_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programmes',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='autodidact.Programme'),
            preserve_default=False,
        ),
    ]
