# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0017_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=False, help_text='Inactive assignments are not visible to students'),
        ),
    ]
