# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0017_auto_20171025_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programme',
            new_name='Program',
        ),
    ]
