# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0018_auto_20160309_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Only visible to teacher'), (2, 'Visible to students in class'), (3, 'Visible to everyone')], default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, help_text='This field supports <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, help_text='This field supports <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
