# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0019_auto_20171025_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='autodidact.Program'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
