# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0020_auto_20160413_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='order',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='order',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='order',
            new_name='number',
        ),
    ]
