# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0022_auto_20160413_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='This field supports <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='autodidact.Course')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
