# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import pandocfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0024_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
    ]
