# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:05
from __future__ import unicode_literals

import sys
from django.db import migrations, models
import pandocfield.fields

from autodidact.models import Clarification, Course, Page, Session, Step, Topic

def resave_all_text_fields(*args, **kwargs):
    for klass in [Clarification, Course, Page, Session, Step, Topic]:
        print("\nRe-saving all {} objects.".format(klass.__name__), end='')
        for obj in klass.objects.all():
            sys.stdout.write('.')
            sys.stdout.flush()
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0025_auto_20160531_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarification',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='_content_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='session',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='_description_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='clarification',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=pandocfield.fields.PandocField(auto_create_html_field=False, blank=True),
        ),

        migrations.RunPython(resave_all_text_fields, migrations.RunPython.noop),
    ]
