# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0026_auto_20160531_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave this field blank for the homepage', unique=True),
        ),
    ]
