#!/bin/sh

set -e

#DEBHELPER#

KEYFILE=/etc/bps/secret.key
UPLOADS=/var/lib/bps/uploads

case $1 in
    configure)

        if [ ! -e "$KEYFILE" ]
	then
	    umask 027
	    makepasswd --chars=50 > "$KEYFILE"
	    chgrp www-data "$KEYFILE"
	fi

        if [ ! -e "$UPLOADS"]
        then
            mkdir "$UPLOADS"
            chown www-data:www-data "$UPLOADS"
        fi

	project_dir=`python -c 'import os,bps; print os.path.dirname(bps.__file__)'`
	sed -i "s:%PROJECT_DIR%:$project_dir:" /etc/apache2/conf-available/bps.conf

	su www-data -s /bin/sh -c 'yes yes | manage.py collectstatic'
        su www-data -s /bin/sh -c 'manage.py migrate'

esac
