#!/bin/sh

set -e

#DEBHELPER#

case $1 in configure)
	if [ ! -e /etc/bps/secret.py ]
	then
		(
			umask 027
			echo "SECRET_KEY = '$(makepasswd --chars=50)'" >/etc/bps/secret.py
			chgrp www-data /etc/bps/secret.py
		)
	fi
	(
		cd `python -c 'import os,bps; print os.path.dirname(bps.__file__)'`
		python manage.py collectstatic
	)
esac
